package lookup

//IsStopWord returns true if word is a stop-word
func IsStopWord(word string) bool {
	return stopWords[word]
}

//IsVowel returns true if `c` is a vowel
func IsVowel(c uint8) bool {
	return vowels[c]
}

//IsSEnding returns true if `c` is a s-ending
func IsSEnding(c uint8) bool {
	return sEnding[c]
}

//IsStEnding returns true if `c` is a st-ending
func IsStEnding(c uint8) bool {
	return stEnding[c]
}

// äöü -> AOU so they can be represented as ascii chars
var vowels = map[uint8]bool{
	'a': true,
	'e': true,
	'i': true,
	'o': true,
	'u': true,
	'y': true,
	'A': true,
	'O': true,
	'V': true,
}

var sEnding = map[uint8]bool{
	'b': true,
	'd': true,
	'f': true,
	'g': true,
	'h': true,
	'k': true,
	'l': true,
	'm': true,
	'n': true,
	'r': true,
	't': true,
}

var stEnding = map[uint8]bool{
	'b': true,
	'd': true,
	'f': true,
	'g': true,
	'h': true,
	'k': true,
	'l': true,
	'm': true,
	'n': true,
	't': true,
}

var stopWords = map[string]bool{
	"aber":      true,
	"alle":      true,
	"allem":     true,
	"allen":     true,
	"aller":     true,
	"alles":     true,
	"als":       true,
	"also":      true,
	"am":        true,
	"an":        true,
	"ander":     true,
	"andere":    true,
	"anderem":   true,
	"anderen":   true,
	"anderer":   true,
	"anderes":   true,
	"anderm":    true,
	"andern":    true,
	"anderr":    true,
	"anders":    true,
	"auch":      true,
	"auf":       true,
	"aus":       true,
	"bei":       true,
	"bin":       true,
	"bis":       true,
	"bist":      true,
	"da":        true,
	"damit":     true,
	"dann":      true,
	"der":       true,
	"den":       true,
	"des":       true,
	"dem":       true,
	"die":       true,
	"das":       true,
	"daß":       true,
	"derselbe":  true,
	"derselben": true,
	"denselben": true,
	"desselben": true,
	"demselben": true,
	"dieselbe":  true,
	"dieselben": true,
	"dasselbe":  true,
	"dazu":      true,
	"dein":      true,
	"deine":     true,
	"deinem":    true,
	"deinen":    true,
	"deiner":    true,
	"deines":    true,
	"denn":      true,
	"derer":     true,
	"dessen":    true,
	"dich":      true,
	"dir":       true,
	"du":        true,
	"dies":      true,
	"diese":     true,
	"diesem":    true,
	"diesen":    true,
	"dieser":    true,
	"dieses":    true,
	"doch":      true,
	"dort":      true,
	"durch":     true,
	"ein":       true,
	"eine":      true,
	"einem":     true,
	"einen":     true,
	"einer":     true,
	"eines":     true,
	"einig":     true,
	"einige":    true,
	"einigem":   true,
	"einigen":   true,
	"einiger":   true,
	"einiges":   true,
	"einmal":    true,
	"er":        true,
	"ihn":       true,
	"ihm":       true,
	"es":        true,
	"etwas":     true,
	"euer":      true,
	"eure":      true,
	"eurem":     true,
	"euren":     true,
	"eurer":     true,
	"eures":     true,
	"für":       true,
	"gegen":     true,
	"gewesen":   true,
	"hab":       true,
	"habe":      true,
	"haben":     true,
	"hat":       true,
	"hatte":     true,
	"hatten":    true,
	"hier":      true,
	"hin":       true,
	"hinter":    true,
	"ich":       true,
	"mich":      true,
	"mir":       true,
	"ihr":       true,
	"ihre":      true,
	"ihrem":     true,
	"ihren":     true,
	"ihrer":     true,
	"ihres":     true,
	"euch":      true,
	"im":        true,
	"in":        true,
	"indem":     true,
	"ins":       true,
	"ist":       true,
	"jede":      true,
	"jedem":     true,
	"jeden":     true,
	"jeder":     true,
	"jedes":     true,
	"jene":      true,
	"jenem":     true,
	"jenen":     true,
	"jener":     true,
	"jenes":     true,
	"jetzt":     true,
	"kann":      true,
	"kein":      true,
	"keine":     true,
	"keinem":    true,
	"keinen":    true,
	"keiner":    true,
	"keines":    true,
	"können":    true,
	"könnte":    true,
	"machen":    true,
	"man":       true,
	"manche":    true,
	"manchem":   true,
	"manchen":   true,
	"mancher":   true,
	"manches":   true,
	"mein":      true,
	"meine":     true,
	"meinem":    true,
	"meinen":    true,
	"meiner":    true,
	"meines":    true,
	"mit":       true,
	"muss":      true,
	"musste":    true,
	"nach":      true,
	"nicht":     true,
	"nichts":    true,
	"noch":      true,
	"nun":       true,
	"nur":       true,
	"ob":        true,
	"oder":      true,
	"ohne":      true,
	"sehr":      true,
	"sein":      true,
	"seine":     true,
	"seinem":    true,
	"seinen":    true,
	"seiner":    true,
	"seines":    true,
	"selbst":    true,
	"sich":      true,
	"sie":       true,
	"ihnen":     true,
	"sind":      true,
	"so":        true,
	"solche":    true,
	"solchem":   true,
	"solchen":   true,
	"solcher":   true,
	"solches":   true,
	"soll":      true,
	"sollte":    true,
	"sondern":   true,
	"sonst":     true,
	"über":      true,
	"um":        true,
	"und":       true,
	"uns":       true,
	"unse":      true,
	"unsem":     true,
	"unsen":     true,
	"unser":     true,
	"unses":     true,
	"unter":     true,
	"viel":      true,
	"vom":       true,
	"von":       true,
	"vor":       true,
	"während":   true,
	"war":       true,
	"waren":     true,
	"warst":     true,
	"was":       true,
	"weg":       true,
	"weil":      true,
	"weiter":    true,
	"welche":    true,
	"welchem":   true,
	"welchen":   true,
	"welcher":   true,
	"welches":   true,
	"wenn":      true,
	"werde":     true,
	"werden":    true,
	"wie":       true,
	"wieder":    true,
	"will":      true,
	"wir":       true,
	"wird":      true,
	"wirst":     true,
	"wo":        true,
	"wollen":    true,
	"wollte":    true,
	"würde":     true,
	"würden":    true,
	"zu":        true,
	"zum":       true,
	"zur":       true,
	"zwar":      true,
	"zwischen":  true,
}
